name: Svendsen
favicon: null
layout_spectrum: 0.5486720856279135
typography_spectrum: 0.9452867356594652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2906430414877832
  lightness: 0.021495044697076082
  saturation: 0.6650371502619237
  rhythmicContrast: 0.9859531142283231
purpose: []
